// M3U playlist compat endpoints — just return JSON URLs.
// Actual M3U files are generated by worker and served as static from pb_public.

routerAdd("POST", "/api/playlist/generate", (e) => {
    try {
        var bodyStr = toString(e.request.body);
        var body = JSON.parse(bodyStr);
        var slug = (body.slug || "").trim();
        if (!slug) return e.json(400, { message: "slug required" });
        return e.json(200, { message: "ok", url: "/" + slug + ".m3u" });
    } catch (err) {
        return e.json(500, { message: "error: " + err });
    }
});
